# Welcome to Jekyll!

# Website settings
title: "Dash"
description: "Ayushman Dash's blog."
keywords: "dash,blog,Jekyll,github,gh-pages,personal"
baseurl: "/"
url: "http://github-username.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Ayushman Dash'
  first_name: 'Ayushman'
  last_name: 'Dash'
  email: 'dash.ayushman.99@gmail.com'
  facebook_username: 'ayushmanmaku'
  github_username: 'dashayushman'
  head_img: 'static/img/landing/dash.jpg'
  desc: 'I am machine learning engineer with experience in toolkits like scikit-learn, Tensorflow, Keras. I began my career as a full stack web developer and I still enjoy designing User Interfaces. Python, java, node.js, mongoDb and express are my preferred programming langiuages, frameworks and database engines and I have experience in MySQL and java too. I am an extremely fast learner, hard worker and a self-motivated independent developer. I believe that with hard work and sincerity anything can be achieved. I have an affinity towards Artificial Intelligence, Machine Learning, Deep Neural Networks, Information Retrieval, Data Mining and I aim at contributing as much as I can to these fields.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  #- locale: 'zh'
    #flag: 'static/img/flags/China.png'

# blog img path
img_path: 'https://dashayushman.github.io/static/img/blog'

# donate
donate:
  #wechat: 'static/img/pay/wechat.png'
  #alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: dash-blog
  public_key: UDu5POnJPbqKA6ixydW182oSweXgF4HtnhySTxuxGGanwldHpCKshKuO5TAKObRZ

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-86445551-1

# growingIO
gio:
  #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
