# Welcome to Jekyll!

# Website settings
title: "Dash"
description: "Ayushman Dash's blog."
keywords: "dash,blog,Jekyll,github,gh-pages,personal"
baseurl: "https://dashayushman.github.io/"
#baseurl: "/"
url: "https://dashayushman.github.io"
#url: "http://127.0.0.1:4000"

# author
author:
  name: 'Ayushman Dash'
  first_name: 'Ayushman'
  last_name: 'Dash'
  email: 'dash.ayushman.99@gmail.com'
  facebook_username: 'ayushmanmaku'
  github_username: 'dashayushman'
  head_img: 'static/img/landing/dash.jpg'
  desc: 'I am a fast learner, hard worker, and a self-motivated independent developer. I have an affinity towards Artificial Intelligence (specifically Machine Learning and Deep Learning) and I aim at contributing as much as I can to these fields. My research interests are Sequence Learning, Generative Adversarial Networks, Sequence to Sequence Models, Siamese Network, Natural Language Understanding using Deep Learning, and Handwriting Recognition in Air. Apart from my interests in AI I have a keen interest in Web Application development, Music Composition and Production.'

# sections
sections:
  - id: 'about-me'
    nav: '!nav'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    nav: '!nav'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    nav: '!nav'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    nav: '!nav'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'publications'
    nav: 'publications'
    i18n: 'nav.publictations'
    name: 'Publications'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'blog'
    nav: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'cv'
    nav: 'cv'
    i18n: 'nav.cv'
    name: 'Curriculum Vitae'
    tpl: 'blog.html'
    css: 'contact'

  - id: 'links'
    nav: 'nav'
    i18n: 'nav.link'
    name: 'Contact'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  #- locale: 'zh'
    #flag: 'static/img/flags/China.png'

# blog img path
img_path: 'https://dashayushman.github.io/static/img/blog'

# donate
donate:
  #wechat: 'static/img/pay/wechat.png'
  #alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: dash-blog
  public_key: UDu5POnJPbqKA6ixydW182oSweXgF4HtnhySTxuxGGanwldHpCKshKuO5TAKObRZ

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-86445551-1

# growingIO
gio:
  #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
